export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'FETCH_USERS_FAIL';

export const INPUT_HANDLER = 'INPUT_HANDLER';

export const COUNT_HANDLER = 'COUNT_HANDLER';

export const SORT_HANDLER = 'SORT_HANDLER';

export const FAVORITES_HANDLER = 'FAVORITES_HANDLER';